from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^homepage$', 'grumblr.views.homepage',name='homepage'),
    url(r'^user_stream$','grumblr.views.user_stream', name='user_stream'),
    url(r'^user_stream_(?P<id>\d+)$','grumblr.views.specified_user_stream', name='specified_user_stream'),
    url(r'^add_post$','grumblr.views.add_post', name='add_post'),
    url(r'^delete_post/(?P<id>\d+)$', 'grumblr.views.delete_post', name='delete_post'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'grumblr/login.html'}, name='login'),
    url(r'^profile/(?P<id>\d+)$', 'grumblr.views.profile', name='profile'),
    url(r'^edit_profile$','grumblr.views.edit_profile',name='edit_profile'),
    url(r'^search_post$','grumblr.views.search_post', name='search_post'),
    url(r'^search_result$','grumblr.views.search_post', name='search_result'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^registration$', 'grumblr.views.registration', name='registration'),
    url(r'^add_comment$','grumblr.views.add_comment',name='add_comment'),
    url(r'^picture/(?P<id>\d+)$', 'grumblr.views.get_picture', name='picture'),
    url(r'^profile/picture/(?P<id>\d+)$', 'grumblr.views.get_picture', name='picture'),
    url(r'^follow/(?P<id>\d+)$','grumblr.views.follow', name='follow'),
    url(r'^check_update/(?P<post_id>\d+)$','grumblr.views.check_update', name='check_update'),
    url(r'^unfollow/(?P<id>\d+)$','grumblr.views.unfollow', name='unfollow'),
    url(r'^dislike/(?P<id>\d+)$','grumblr.views.dislike_post', name='dislike'),
    url(r'^delete_dislike/(?P<id>\d+)$', 'grumblr.views.delete_dislike', name='delete_dislike'),
    url(r'^delete_comment/(?P<id>\d+)$','grumblr.views.delete_comment', name='delete_comment'),
    url(r'^block_user/(?P<id>\d+)$', 'grumblr.views.block_user', name='block_user'),
    url(r'^unblock_user/(?P<id>\d+)$', 'grumblr.views.unblock_user', name='unblock_user'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'grumblr.views.confirm_registration', name='confirm'),
    url(r'^accounts/password_change/$', 
        'django.contrib.auth.views.password_change', 
        {'post_change_redirect' : '/accounts/password_change/done/'}, 
        name="password_change"), 
    (r'^accounts/password_change/done/$', 
        'django.contrib.auth.views.password_change_done'),

    url(r'^accounts/password_reset/$', 
        'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/accounts/password_reset/mailed/'},
        name="password_reset"),
    (r'^accounts/password_reset/mailed/$',
        'django.contrib.auth.views.password_reset_done'),
    url(r'^accounts/password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/accounts/password_reset/complete/'}, name="password_reset_confirm"),
    (r'^accounts/password_reset/complete/$', 
        'django.contrib.auth.views.password_reset_complete'),
)
